/*
 * Copyright 2026 Amazon.com, Inc. or its affiliates.
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.amazonaws.services.schemaregistry.integrationtests.kafkaconnect.protobuf;

import com.amazonaws.services.schemaregistry.integrationtests.properties.GlueSchemaRegistryConnectionProperties;
import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter;
import com.amazonaws.services.schemaregistry.utils.AWSSchemaRegistryConstants;
import org.apache.kafka.connect.data.Schema;
import org.apache.kafka.connect.data.SchemaAndValue;
import org.apache.kafka.connect.data.SchemaBuilder;
import org.apache.kafka.connect.data.Struct;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.glue.GlueClient;
import software.amazon.awssdk.services.glue.model.DataFormat;
import software.amazon.awssdk.services.glue.model.DeleteSchemaRequest;
import software.amazon.awssdk.services.glue.model.EntityNotFoundException;
import software.amazon.awssdk.services.glue.model.SchemaId;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class ProtobufSchemaConverterIntegrationTest {
    private static final String REGION = GlueSchemaRegistryConnectionProperties.REGION;
    private static final String ENDPOINT = GlueSchemaRegistryConnectionProperties.ENDPOINT;
    private static final String SCHEMA_NAME = "gsr-protobuf-connect-null-" + UUID.randomUUID();
    private static final String TOPIC_NAME = SCHEMA_NAME + "-topic";

    @AfterAll
    public static void tearDown() {
        try (GlueClient glueClient = GlueClient.builder()
                .credentialsProvider(DefaultCredentialsProvider.create())
                .region(Region.of(REGION))
                .endpointOverride(URI.create(ENDPOINT))
                .httpClient(UrlConnectionHttpClient.create())
                .build()) {
            DeleteSchemaRequest request = DeleteSchemaRequest.builder()
                .schemaId(SchemaId.builder()
                    .registryName(AWSSchemaRegistryConstants.DEFAULT_REGISTRY_NAME)
                    .schemaName(SCHEMA_NAME)
                    .build())
                .build();
            glueClient.deleteSchema(request);
        } catch (EntityNotFoundException ignored) {
            // Conversion can fail before creating the schema, leaving nothing to clean up.
        }
    }

    @Test
    public void fromConnectData_roundTripsStructWithoutSchemaParametersThroughGlue() {
        Schema childSchema = SchemaBuilder.struct()
            .name("com.amazonaws.services.schemaregistry.kafkaconnect.autogenerated.Parent.Child")
            .field("value", Schema.STRING_SCHEMA)
            .build();
        Schema parentSchema = SchemaBuilder.struct()
            .name("Parent")
            .field("child", childSchema)
            .build();
        Struct childData = new Struct(childSchema).put("value", "test-value");
        Struct parentData = new Struct(parentSchema).put("child", childData);

        Map<String, Object> configuration = new HashMap<>();
        configuration.put(AWSSchemaRegistryConstants.AWS_REGION, REGION);
        configuration.put(AWSSchemaRegistryConstants.AWS_ENDPOINT, ENDPOINT);
        configuration.put(AWSSchemaRegistryConstants.REGISTRY_NAME,
            AWSSchemaRegistryConstants.DEFAULT_REGISTRY_NAME);
        configuration.put(AWSSchemaRegistryConstants.SCHEMA_NAME, SCHEMA_NAME);
        configuration.put(AWSSchemaRegistryConstants.DATA_FORMAT, DataFormat.PROTOBUF.name());
        configuration.put(AWSSchemaRegistryConstants.SCHEMA_AUTO_REGISTRATION_SETTING, true);
        configuration.put(AWSSchemaRegistryConstants.COMPATIBILITY_SETTING, "NONE");

        ProtobufSchemaConverter converter = new ProtobufSchemaConverter();
        converter.configure(configuration, false);

        byte[] serializedData = converter.fromConnectData(TOPIC_NAME, parentSchema, parentData);
        assertTrue(serializedData.length > 0);

        SchemaAndValue result = converter.toConnectData(TOPIC_NAME, serializedData);
        assertTrue(result.value() instanceof Struct);
        Struct resultChild = ((Struct) result.value()).getStruct("child");
        assertEquals("test-value", resultChild.getString("value"));
    }
}
